# cloudbuild.yaml － 走 Artifact Registry + Cloud Run
substitutions:
  _REGION: asia-east1
  _SERVICE: ticketsearch
  _REPO: cloud-run-source-deploy
  _IMAGE: asia-east1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$COMMIT_SHA

steps:
# Build image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_IMAGE}', '.']

# Push image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_IMAGE}']

# Deploy to Cloud Run（連同 Secrets / 環境變數）
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - run
    - deploy
    - '${_SERVICE}'
    - --image
    - '${_IMAGE}'
    - --region
    - '${_REGION}'
    - --allow-unauthenticated
    - --set-secrets
    - 'LINE_CHANNEL_ACCESS_TOKEN=line-channel-token:latest,LINE_CHANNEL_SECRET=line-channel-secret:latest,CRON_KEY=cron-key:latest'
    - --set-env-vars
    - 'DEFAULT_INTERVAL=15'

images:
- '${_IMAGE}'
