options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: asia-east1
  _SERVICE: ticketsearch
  _REPO: cloud-run-source-deploy

images:
- 'asia-east1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA'

steps:
# Build
- name: gcr.io/cloud-builders/docker
  args: ['build','-t','asia-east1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA','.']

# Push
- name: gcr.io/cloud-builders/docker
  args: ['push','asia-east1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA']

# Deploy
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    - run
    - deploy
    - '${_SERVICE}'
    - '--image'
    - 'asia-east1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA'
    - '--region'
    - '${_REGION}'
    - '--allow-unauthenticated'
    - '--set-secrets'
    - 'LINE_CHANNEL_ACCESS_TOKEN=line-channel-token:latest,LINE_CHANNEL_SECRET=line-channel-secret:latest,CRON_KEY=cron-key:latest'
    - '--update-env-vars'
    - 'DEFAULT_INTERVAL=15'
